"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .applicationoauth2installparamsresponse import (
    ApplicationOAuth2InstallParamsResponse,
    ApplicationOAuth2InstallParamsResponseTypedDict,
)
from discord_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class ApplicationIntegrationTypeConfigurationResponseTypedDict(TypedDict):
    oauth2_install_params: NotRequired[
        Nullable[ApplicationOAuth2InstallParamsResponseTypedDict]
    ]


class ApplicationIntegrationTypeConfigurationResponse(BaseModel):
    oauth2_install_params: OptionalNullable[ApplicationOAuth2InstallParamsResponse] = (
        UNSET
    )

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["oauth2_install_params"]
        nullable_fields = ["oauth2_install_params"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in self.model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
