"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from discord_sdk.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class ApplicationOAuth2InstallParamsResponseTypedDict(TypedDict):
    scopes: List[str]
    permissions: str


class ApplicationOAuth2InstallParamsResponse(BaseModel):
    scopes: List[str]

    permissions: str
