"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from discord_sdk.types import BaseModel
from discord_sdk.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, TypedDict


class ChannelPermissionOverwriteResponseTypedDict(TypedDict):
    id: str
    allow: str
    deny: str
    type: Literal[0]


class ChannelPermissionOverwriteResponse(BaseModel):
    id: str

    allow: str

    deny: str

    TYPE: Annotated[
        Annotated[Literal[0], AfterValidator(validate_const(0))],
        pydantic.Field(alias="type"),
    ] = 0
