"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .privatechannelresponse import (
    PrivateChannelResponse,
    PrivateChannelResponseTypedDict,
)
from .privategroupchannelresponse import (
    PrivateGroupChannelResponse,
    PrivateGroupChannelResponseTypedDict,
)
from typing import Union


CreateDmResponseBodyTypedDict = Union[
    PrivateChannelResponseTypedDict, PrivateGroupChannelResponseTypedDict
]
r"""200 response for create_dm"""


CreateDmResponseBody = Union[PrivateChannelResponse, PrivateGroupChannelResponse]
r"""200 response for create_dm"""
