"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .creategroupdminviterequest import (
    CreateGroupDMInviteRequest,
    CreateGroupDMInviteRequestTypedDict,
)
from .createguildinviterequest import (
    CreateGuildInviteRequest,
    CreateGuildInviteRequestTypedDict,
)
from .friendinviteresponse import FriendInviteResponse, FriendInviteResponseTypedDict
from .groupdminviteresponse import GroupDMInviteResponse, GroupDMInviteResponseTypedDict
from .guildinviteresponse import GuildInviteResponse, GuildInviteResponseTypedDict
from discord_sdk.types import BaseModel
from discord_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing import Union
from typing_extensions import Annotated, TypedDict


CreateChannelInviteRequestBodyTypedDict = Union[
    CreateGroupDMInviteRequestTypedDict, CreateGuildInviteRequestTypedDict
]


CreateChannelInviteRequestBody = Union[
    CreateGroupDMInviteRequest, CreateGuildInviteRequest
]


class CreateChannelInviteRequestTypedDict(TypedDict):
    channel_id: str
    request_body: CreateChannelInviteRequestBodyTypedDict


class CreateChannelInviteRequest(BaseModel):
    channel_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    request_body: Annotated[
        CreateChannelInviteRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


CreateChannelInviteResponseBodyTypedDict = Union[
    GroupDMInviteResponseTypedDict,
    FriendInviteResponseTypedDict,
    GuildInviteResponseTypedDict,
]
r"""200 response for create_channel_invite"""


CreateChannelInviteResponseBody = Union[
    GroupDMInviteResponse, FriendInviteResponse, GuildInviteResponse
]
r"""200 response for create_channel_invite"""
