"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from discord_sdk.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class DefaultKeywordListTriggerMetadataResponseTypedDict(TypedDict):
    allow_list: List[str]
    presets: List[int]


class DefaultKeywordListTriggerMetadataResponse(BaseModel):
    allow_list: List[str]

    presets: List[int]
