"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from discord_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from discord_sdk.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, NotRequired, TypedDict


class EntitlementResponseTypedDict(TypedDict):
    id: str
    sku_id: str
    application_id: str
    user_id: str
    deleted: bool
    guild_id: NotRequired[Nullable[str]]
    starts_at: NotRequired[Nullable[datetime]]
    ends_at: NotRequired[Nullable[datetime]]
    type: Literal[8]
    fulfilled_at: NotRequired[Nullable[datetime]]
    fulfillment_status: Nullable[Literal[0]]
    consumed: NotRequired[Nullable[bool]]


class EntitlementResponse(BaseModel):
    id: str

    sku_id: str

    application_id: str

    user_id: str

    deleted: bool

    guild_id: OptionalNullable[str] = UNSET

    starts_at: OptionalNullable[datetime] = UNSET

    ends_at: OptionalNullable[datetime] = UNSET

    TYPE: Annotated[
        Annotated[Literal[8], AfterValidator(validate_const(8))],
        pydantic.Field(alias="type"),
    ] = 8

    fulfilled_at: OptionalNullable[datetime] = UNSET

    FULFILLMENT_STATUS: Annotated[
        Annotated[OptionalNullable[Literal[0]], AfterValidator(validate_const(0))],
        pydantic.Field(alias="fulfillment_status"),
    ] = 0

    consumed: OptionalNullable[bool] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "guild_id",
            "starts_at",
            "ends_at",
            "fulfilled_at",
            "fulfillment_status",
            "consumed",
        ]
        nullable_fields = [
            "guild_id",
            "starts_at",
            "ends_at",
            "fulfilled_at",
            "fulfillment_status",
            "consumed",
        ]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in self.model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
