"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from discord_sdk.types import BaseModel
from typing_extensions import TypedDict


class ErrorTypedDict(TypedDict):
    r"""A single error, either for an API response or a specific field."""

    code: int
    r"""Discord internal error code. See error code reference"""
    message: str
    r"""Human-readable error message"""


class Error(BaseModel):
    r"""A single error, either for an API response or a specific field."""

    code: int
    r"""Discord internal error code. See error code reference"""

    message: str
    r"""Human-readable error message"""
