"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .innererrors import InnerErrors, InnerErrorsTypedDict
from typing import Dict, Union


ErrorDetailsTypedDict = Union[InnerErrorsTypedDict, Dict[str, "ErrorDetailsTypedDict"]]


ErrorDetails = Union[InnerErrors, Dict[str, "ErrorDetails"]]
