"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .flagtochannelactionmetadataresponse import (
    FlagToChannelActionMetadataResponse,
    FlagToChannelActionMetadataResponseTypedDict,
)
from discord_sdk.types import BaseModel
from discord_sdk.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, TypedDict


class FlagToChannelActionResponseTypedDict(TypedDict):
    metadata: FlagToChannelActionMetadataResponseTypedDict
    type: Literal[1]


class FlagToChannelActionResponse(BaseModel):
    metadata: FlagToChannelActionMetadataResponse

    TYPE: Annotated[
        Annotated[Literal[1], AfterValidator(validate_const(1))],
        pydantic.Field(alias="type"),
    ] = 1
