"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .gatewaybotsessionstartlimitresponse import (
    GatewayBotSessionStartLimitResponse,
    GatewayBotSessionStartLimitResponseTypedDict,
)
from discord_sdk.types import BaseModel
from typing_extensions import TypedDict


class GatewayBotResponseTypedDict(TypedDict):
    url: str
    session_start_limit: GatewayBotSessionStartLimitResponseTypedDict
    shards: int


class GatewayBotResponse(BaseModel):
    url: str

    session_start_limit: GatewayBotSessionStartLimitResponse

    shards: int
