"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from discord_sdk.types import BaseModel
from typing_extensions import TypedDict


class GatewayBotSessionStartLimitResponseTypedDict(TypedDict):
    max_concurrency: int
    remaining: int
    reset_after: int
    total: int


class GatewayBotSessionStartLimitResponse(BaseModel):
    max_concurrency: int

    remaining: int

    reset_after: int

    total: int
