"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .externalscheduledeventresponse import (
    ExternalScheduledEventResponse,
    ExternalScheduledEventResponseTypedDict,
)
from .stagescheduledeventresponse import (
    StageScheduledEventResponse,
    StageScheduledEventResponseTypedDict,
)
from .voicescheduledeventresponse import (
    VoiceScheduledEventResponse,
    VoiceScheduledEventResponseTypedDict,
)
from discord_sdk.types import BaseModel
from discord_sdk.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
from typing import Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


class GetGuildScheduledEventRequestTypedDict(TypedDict):
    guild_id: str
    guild_scheduled_event_id: str
    with_user_count: NotRequired[bool]


class GetGuildScheduledEventRequest(BaseModel):
    guild_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    guild_scheduled_event_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    with_user_count: Annotated[
        Optional[bool],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None


GetGuildScheduledEventResponseBodyTypedDict = Union[
    ExternalScheduledEventResponseTypedDict,
    StageScheduledEventResponseTypedDict,
    VoiceScheduledEventResponseTypedDict,
]
r"""200 response for get_guild_scheduled_event"""


GetGuildScheduledEventResponseBody = Union[
    ExternalScheduledEventResponse,
    StageScheduledEventResponse,
    VoiceScheduledEventResponse,
]
r"""200 response for get_guild_scheduled_event"""
