"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .applicationincomingwebhookresponse import (
    ApplicationIncomingWebhookResponse,
    ApplicationIncomingWebhookResponseTypedDict,
)
from .channelfollowerwebhookresponse import (
    ChannelFollowerWebhookResponse,
    ChannelFollowerWebhookResponseTypedDict,
)
from .guildincomingwebhookresponse import (
    GuildIncomingWebhookResponse,
    GuildIncomingWebhookResponseTypedDict,
)
from discord_sdk.types import BaseModel
from discord_sdk.utils import FieldMetadata, PathParamMetadata
from typing import Union
from typing_extensions import Annotated, TypedDict


class GetGuildWebhooksRequestTypedDict(TypedDict):
    guild_id: str


class GetGuildWebhooksRequest(BaseModel):
    guild_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


GetGuildWebhooksResponseBodyTypedDict = Union[
    ApplicationIncomingWebhookResponseTypedDict,
    ChannelFollowerWebhookResponseTypedDict,
    GuildIncomingWebhookResponseTypedDict,
]


GetGuildWebhooksResponseBody = Union[
    ApplicationIncomingWebhookResponse,
    ChannelFollowerWebhookResponse,
    GuildIncomingWebhookResponse,
]
