"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from discord_sdk.types import BaseModel
from discord_sdk.utils import (
    FieldMetadata,
    PathParamMetadata,
    QueryParamMetadata,
    SecurityMetadata,
)
from typing import List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


class GetEntitlementsSecurityTypedDict(TypedDict):
    bot_token: NotRequired[str]


class GetEntitlementsSecurity(BaseModel):
    bot_token: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="apiKey",
                sub_type="header",
                field_name="Authorization",
            )
        ),
    ] = None


SkuIdsTypedDict = Union[str, List[str]]


SkuIds = Union[str, List[str]]


class GetEntitlementsRequestTypedDict(TypedDict):
    application_id: str
    sku_ids: SkuIdsTypedDict
    user_id: NotRequired[str]
    guild_id: NotRequired[str]
    before: NotRequired[str]
    after: NotRequired[str]
    limit: NotRequired[int]
    exclude_ended: NotRequired[bool]
    only_active: NotRequired[bool]


class GetEntitlementsRequest(BaseModel):
    application_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    sku_ids: Annotated[
        SkuIds, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]

    user_id: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    guild_id: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    before: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    after: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    exclude_ended: Annotated[
        Optional[bool],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    only_active: Annotated[
        Optional[bool],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
