"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .applicationincomingwebhookresponse import (
    ApplicationIncomingWebhookResponse,
    ApplicationIncomingWebhookResponseTypedDict,
)
from .channelfollowerwebhookresponse import (
    ChannelFollowerWebhookResponse,
    ChannelFollowerWebhookResponseTypedDict,
)
from .guildincomingwebhookresponse import (
    GuildIncomingWebhookResponse,
    GuildIncomingWebhookResponseTypedDict,
)
from discord_sdk.types import BaseModel
from discord_sdk.utils import FieldMetadata, PathParamMetadata
from typing import Union
from typing_extensions import Annotated, TypedDict


class GetWebhookRequestTypedDict(TypedDict):
    webhook_id: str


class GetWebhookRequest(BaseModel):
    webhook_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


GetWebhookResponseBodyTypedDict = Union[
    ApplicationIncomingWebhookResponseTypedDict,
    ChannelFollowerWebhookResponseTypedDict,
    GuildIncomingWebhookResponseTypedDict,
]
r"""200 response for get_webhook"""


GetWebhookResponseBody = Union[
    ApplicationIncomingWebhookResponse,
    ChannelFollowerWebhookResponse,
    GuildIncomingWebhookResponse,
]
r"""200 response for get_webhook"""
