"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .defaultkeywordruleresponse import (
    DefaultKeywordRuleResponse,
    DefaultKeywordRuleResponseTypedDict,
)
from .keywordruleresponse import KeywordRuleResponse, KeywordRuleResponseTypedDict
from .mentionspamruleresponse import (
    MentionSpamRuleResponse,
    MentionSpamRuleResponseTypedDict,
)
from .mlspamruleresponse import MLSpamRuleResponse, MLSpamRuleResponseTypedDict
from .spamlinkruleresponse import SpamLinkRuleResponse, SpamLinkRuleResponseTypedDict
from discord_sdk.types import BaseModel
from discord_sdk.utils import FieldMetadata, PathParamMetadata
from typing import Union
from typing_extensions import Annotated, TypedDict


class GetAutoModerationRuleRequestTypedDict(TypedDict):
    guild_id: str
    rule_id: str


class GetAutoModerationRuleRequest(BaseModel):
    guild_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    rule_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


GetAutoModerationRuleResponseBodyTypedDict = Union[
    DefaultKeywordRuleResponseTypedDict,
    KeywordRuleResponseTypedDict,
    MLSpamRuleResponseTypedDict,
    MentionSpamRuleResponseTypedDict,
    SpamLinkRuleResponseTypedDict,
]
r"""200 response for get_auto_moderation_rule"""


GetAutoModerationRuleResponseBody = Union[
    DefaultKeywordRuleResponse,
    KeywordRuleResponse,
    MLSpamRuleResponse,
    MentionSpamRuleResponse,
    SpamLinkRuleResponse,
]
r"""200 response for get_auto_moderation_rule"""
