"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .guildstickerresponse import GuildStickerResponse, GuildStickerResponseTypedDict
from .standardstickerresponse import (
    StandardStickerResponse,
    StandardStickerResponseTypedDict,
)
from discord_sdk.types import BaseModel
from discord_sdk.utils import FieldMetadata, PathParamMetadata
from typing import Union
from typing_extensions import Annotated, TypedDict


class GetStickerRequestTypedDict(TypedDict):
    sticker_id: str


class GetStickerRequest(BaseModel):
    sticker_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


GetStickerResponseBodyTypedDict = Union[
    StandardStickerResponseTypedDict, GuildStickerResponseTypedDict
]
r"""200 response for get_sticker"""


GetStickerResponseBody = Union[StandardStickerResponse, GuildStickerResponse]
r"""200 response for get_sticker"""
