"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .githubauthor import GithubAuthor, GithubAuthorTypedDict
from discord_sdk.types import BaseModel
from typing_extensions import TypedDict


class GithubCommitTypedDict(TypedDict):
    id: str
    url: str
    message: str
    author: GithubAuthorTypedDict


class GithubCommit(BaseModel):
    id: str

    url: str

    message: str

    author: GithubAuthor
