"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .applicationcommandresponse import (
    ApplicationCommandResponse,
    ApplicationCommandResponseTypedDict,
)
from .applicationincomingwebhookresponse import (
    ApplicationIncomingWebhookResponse,
    ApplicationIncomingWebhookResponseTypedDict,
)
from .auditlogentryresponse import AuditLogEntryResponse, AuditLogEntryResponseTypedDict
from .channelfollowerwebhookresponse import (
    ChannelFollowerWebhookResponse,
    ChannelFollowerWebhookResponseTypedDict,
)
from .defaultkeywordruleresponse import (
    DefaultKeywordRuleResponse,
    DefaultKeywordRuleResponseTypedDict,
)
from .externalscheduledeventresponse import (
    ExternalScheduledEventResponse,
    ExternalScheduledEventResponseTypedDict,
)
from .guildincomingwebhookresponse import (
    GuildIncomingWebhookResponse,
    GuildIncomingWebhookResponseTypedDict,
)
from .keywordruleresponse import KeywordRuleResponse, KeywordRuleResponseTypedDict
from .mentionspamruleresponse import (
    MentionSpamRuleResponse,
    MentionSpamRuleResponseTypedDict,
)
from .mlspamruleresponse import MLSpamRuleResponse, MLSpamRuleResponseTypedDict
from .partialdiscordintegrationresponse import (
    PartialDiscordIntegrationResponse,
    PartialDiscordIntegrationResponseTypedDict,
)
from .partialexternalconnectionintegrationresponse import (
    PartialExternalConnectionIntegrationResponse,
    PartialExternalConnectionIntegrationResponseTypedDict,
)
from .partialguildsubscriptionintegrationresponse import (
    PartialGuildSubscriptionIntegrationResponse,
    PartialGuildSubscriptionIntegrationResponseTypedDict,
)
from .spamlinkruleresponse import SpamLinkRuleResponse, SpamLinkRuleResponseTypedDict
from .stagescheduledeventresponse import (
    StageScheduledEventResponse,
    StageScheduledEventResponseTypedDict,
)
from .threadresponse import ThreadResponse, ThreadResponseTypedDict
from .userresponse import UserResponse, UserResponseTypedDict
from .voicescheduledeventresponse import (
    VoiceScheduledEventResponse,
    VoiceScheduledEventResponseTypedDict,
)
from discord_sdk.types import BaseModel
from typing import List, Union
from typing_extensions import TypedDict


IntegrationsTypedDict = Union[
    PartialExternalConnectionIntegrationResponseTypedDict,
    PartialGuildSubscriptionIntegrationResponseTypedDict,
    PartialDiscordIntegrationResponseTypedDict,
]


Integrations = Union[
    PartialExternalConnectionIntegrationResponse,
    PartialGuildSubscriptionIntegrationResponse,
    PartialDiscordIntegrationResponse,
]


WebhooksModelTypedDict = Union[
    ApplicationIncomingWebhookResponseTypedDict,
    ChannelFollowerWebhookResponseTypedDict,
    GuildIncomingWebhookResponseTypedDict,
]


WebhooksModel = Union[
    ApplicationIncomingWebhookResponse,
    ChannelFollowerWebhookResponse,
    GuildIncomingWebhookResponse,
]


GuildScheduledEventsTypedDict = Union[
    ExternalScheduledEventResponseTypedDict,
    StageScheduledEventResponseTypedDict,
    VoiceScheduledEventResponseTypedDict,
]


GuildScheduledEvents = Union[
    ExternalScheduledEventResponse,
    StageScheduledEventResponse,
    VoiceScheduledEventResponse,
]


AutoModerationRulesModelTypedDict = Union[
    DefaultKeywordRuleResponseTypedDict,
    KeywordRuleResponseTypedDict,
    MLSpamRuleResponseTypedDict,
    MentionSpamRuleResponseTypedDict,
    SpamLinkRuleResponseTypedDict,
]


AutoModerationRulesModel = Union[
    DefaultKeywordRuleResponse,
    KeywordRuleResponse,
    MLSpamRuleResponse,
    MentionSpamRuleResponse,
    SpamLinkRuleResponse,
]


class GuildAuditLogResponseTypedDict(TypedDict):
    audit_log_entries: List[AuditLogEntryResponseTypedDict]
    users: List[UserResponseTypedDict]
    integrations: List[IntegrationsTypedDict]
    webhooks: List[WebhooksModelTypedDict]
    guild_scheduled_events: List[GuildScheduledEventsTypedDict]
    threads: List[ThreadResponseTypedDict]
    application_commands: List[ApplicationCommandResponseTypedDict]
    auto_moderation_rules: List[AutoModerationRulesModelTypedDict]


class GuildAuditLogResponse(BaseModel):
    audit_log_entries: List[AuditLogEntryResponse]

    users: List[UserResponse]

    integrations: List[Integrations]

    webhooks: List[WebhooksModel]

    guild_scheduled_events: List[GuildScheduledEvents]

    threads: List[ThreadResponse]

    application_commands: List[ApplicationCommandResponse]

    auto_moderation_rules: List[AutoModerationRulesModel]
