"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .createguildrequestchannelitem import (
    CreateGuildRequestChannelItem,
    CreateGuildRequestChannelItemTypedDict,
)
from .createguildrequestroleitem import (
    CreateGuildRequestRoleItem,
    CreateGuildRequestRoleItemTypedDict,
)
from discord_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from discord_sdk.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import List, Literal
from typing_extensions import Annotated, NotRequired, TypedDict


class GuildCreateRequestTypedDict(TypedDict):
    name: str
    description: NotRequired[Nullable[str]]
    region: NotRequired[Nullable[str]]
    icon: NotRequired[Nullable[str]]
    verification_level: Nullable[Literal[0]]
    default_message_notifications: Nullable[Literal[0]]
    explicit_content_filter: Nullable[Literal[0]]
    preferred_locale: Nullable[Literal["ar"]]
    afk_timeout: Nullable[Literal[60]]
    roles: NotRequired[Nullable[List[CreateGuildRequestRoleItemTypedDict]]]
    channels: NotRequired[Nullable[List[CreateGuildRequestChannelItemTypedDict]]]
    afk_channel_id: NotRequired[Nullable[str]]
    system_channel_id: NotRequired[Nullable[str]]
    system_channel_flags: NotRequired[Nullable[int]]


class GuildCreateRequest(BaseModel):
    name: str

    description: OptionalNullable[str] = UNSET

    region: OptionalNullable[str] = UNSET

    icon: OptionalNullable[str] = UNSET

    VERIFICATION_LEVEL: Annotated[
        Annotated[OptionalNullable[Literal[0]], AfterValidator(validate_const(0))],
        pydantic.Field(alias="verification_level"),
    ] = 0

    DEFAULT_MESSAGE_NOTIFICATIONS: Annotated[
        Annotated[OptionalNullable[Literal[0]], AfterValidator(validate_const(0))],
        pydantic.Field(alias="default_message_notifications"),
    ] = 0

    EXPLICIT_CONTENT_FILTER: Annotated[
        Annotated[OptionalNullable[Literal[0]], AfterValidator(validate_const(0))],
        pydantic.Field(alias="explicit_content_filter"),
    ] = 0

    PREFERRED_LOCALE: Annotated[
        Annotated[
            OptionalNullable[Literal["ar"]], AfterValidator(validate_const("ar"))
        ],
        pydantic.Field(alias="preferred_locale"),
    ] = "ar"

    AFK_TIMEOUT: Annotated[
        Annotated[OptionalNullable[Literal[60]], AfterValidator(validate_const(60))],
        pydantic.Field(alias="afk_timeout"),
    ] = 60

    roles: OptionalNullable[List[CreateGuildRequestRoleItem]] = UNSET

    channels: OptionalNullable[List[CreateGuildRequestChannelItem]] = UNSET

    afk_channel_id: OptionalNullable[str] = UNSET

    system_channel_id: OptionalNullable[str] = UNSET

    system_channel_flags: OptionalNullable[int] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "description",
            "region",
            "icon",
            "verification_level",
            "default_message_notifications",
            "explicit_content_filter",
            "preferred_locale",
            "afk_timeout",
            "roles",
            "channels",
            "afk_channel_id",
            "system_channel_id",
            "system_channel_flags",
        ]
        nullable_fields = [
            "description",
            "region",
            "icon",
            "verification_level",
            "default_message_notifications",
            "explicit_content_filter",
            "preferred_locale",
            "afk_timeout",
            "roles",
            "channels",
            "afk_channel_id",
            "system_channel_id",
            "system_channel_flags",
        ]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in self.model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
