"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from discord_sdk.types import BaseModel
from typing_extensions import TypedDict


class GuildProductPurchaseResponseTypedDict(TypedDict):
    listing_id: str
    product_name: str


class GuildProductPurchaseResponse(BaseModel):
    listing_id: str

    product_name: str
