"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .channelpermissionoverwriteresponse import (
    ChannelPermissionOverwriteResponse,
    ChannelPermissionOverwriteResponseTypedDict,
)
from .defaultreactionemojiresponse import (
    DefaultReactionEmojiResponse,
    DefaultReactionEmojiResponseTypedDict,
)
from .forumtagresponse import ForumTagResponse, ForumTagResponseTypedDict
from datetime import datetime
from discord_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from discord_sdk.utils import validate_const
from enum import Enum
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import List, Literal
from typing_extensions import Annotated, NotRequired, TypedDict


class GuildChannelResponseType(int, Enum):
    ZERO = 0
    TWO = 2
    FOUR = 4
    FIVE = 5
    THIRTEEN = 13
    FOURTEEN = 14
    FIFTEEN = 15


class GuildChannelResponseTypedDict(TypedDict):
    id: str
    type: GuildChannelResponseType
    flags: int
    guild_id: str
    name: str
    position: int
    last_message_id: NotRequired[Nullable[str]]
    last_pin_timestamp: NotRequired[Nullable[datetime]]
    parent_id: NotRequired[Nullable[str]]
    rate_limit_per_user: NotRequired[Nullable[int]]
    bitrate: NotRequired[Nullable[int]]
    user_limit: NotRequired[Nullable[int]]
    rtc_region: NotRequired[Nullable[str]]
    video_quality_mode: Nullable[Literal[1]]
    permissions: NotRequired[Nullable[str]]
    topic: NotRequired[Nullable[str]]
    default_auto_archive_duration: Nullable[Literal[60]]
    default_thread_rate_limit_per_user: NotRequired[Nullable[int]]
    permission_overwrites: NotRequired[
        Nullable[List[ChannelPermissionOverwriteResponseTypedDict]]
    ]
    nsfw: NotRequired[Nullable[bool]]
    available_tags: NotRequired[Nullable[List[ForumTagResponseTypedDict]]]
    default_reaction_emoji: NotRequired[Nullable[DefaultReactionEmojiResponseTypedDict]]
    default_sort_order: Nullable[Literal[0]]
    default_forum_layout: Nullable[Literal[0]]
    hd_streaming_until: NotRequired[Nullable[datetime]]
    hd_streaming_buyer_id: NotRequired[Nullable[str]]


class GuildChannelResponse(BaseModel):
    id: str

    type: GuildChannelResponseType

    flags: int

    guild_id: str

    name: str

    position: int

    last_message_id: OptionalNullable[str] = UNSET

    last_pin_timestamp: OptionalNullable[datetime] = UNSET

    parent_id: OptionalNullable[str] = UNSET

    rate_limit_per_user: OptionalNullable[int] = UNSET

    bitrate: OptionalNullable[int] = UNSET

    user_limit: OptionalNullable[int] = UNSET

    rtc_region: OptionalNullable[str] = UNSET

    VIDEO_QUALITY_MODE: Annotated[
        Annotated[OptionalNullable[Literal[1]], AfterValidator(validate_const(1))],
        pydantic.Field(alias="video_quality_mode"),
    ] = 1

    permissions: OptionalNullable[str] = UNSET

    topic: OptionalNullable[str] = UNSET

    DEFAULT_AUTO_ARCHIVE_DURATION: Annotated[
        Annotated[OptionalNullable[Literal[60]], AfterValidator(validate_const(60))],
        pydantic.Field(alias="default_auto_archive_duration"),
    ] = 60

    default_thread_rate_limit_per_user: OptionalNullable[int] = UNSET

    permission_overwrites: OptionalNullable[
        List[ChannelPermissionOverwriteResponse]
    ] = UNSET

    nsfw: OptionalNullable[bool] = UNSET

    available_tags: OptionalNullable[List[ForumTagResponse]] = UNSET

    default_reaction_emoji: OptionalNullable[DefaultReactionEmojiResponse] = UNSET

    DEFAULT_SORT_ORDER: Annotated[
        Annotated[OptionalNullable[Literal[0]], AfterValidator(validate_const(0))],
        pydantic.Field(alias="default_sort_order"),
    ] = 0

    DEFAULT_FORUM_LAYOUT: Annotated[
        Annotated[OptionalNullable[Literal[0]], AfterValidator(validate_const(0))],
        pydantic.Field(alias="default_forum_layout"),
    ] = 0

    hd_streaming_until: OptionalNullable[datetime] = UNSET

    hd_streaming_buyer_id: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "last_message_id",
            "last_pin_timestamp",
            "parent_id",
            "rate_limit_per_user",
            "bitrate",
            "user_limit",
            "rtc_region",
            "video_quality_mode",
            "permissions",
            "topic",
            "default_auto_archive_duration",
            "default_thread_rate_limit_per_user",
            "permission_overwrites",
            "nsfw",
            "available_tags",
            "default_reaction_emoji",
            "default_sort_order",
            "default_forum_layout",
            "hd_streaming_until",
            "hd_streaming_buyer_id",
        ]
        nullable_fields = [
            "last_message_id",
            "last_pin_timestamp",
            "parent_id",
            "rate_limit_per_user",
            "bitrate",
            "user_limit",
            "rtc_region",
            "video_quality_mode",
            "permissions",
            "topic",
            "default_auto_archive_duration",
            "default_thread_rate_limit_per_user",
            "permission_overwrites",
            "nsfw",
            "available_tags",
            "default_reaction_emoji",
            "default_sort_order",
            "default_forum_layout",
            "hd_streaming_until",
            "hd_streaming_buyer_id",
        ]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in self.model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
