"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .friendinviteresponse import FriendInviteResponse, FriendInviteResponseTypedDict
from .groupdminviteresponse import GroupDMInviteResponse, GroupDMInviteResponseTypedDict
from .guildinviteresponse import GuildInviteResponse, GuildInviteResponseTypedDict
from discord_sdk.types import BaseModel
from discord_sdk.utils import FieldMetadata, PathParamMetadata
from typing import Union
from typing_extensions import Annotated, TypedDict


class ListChannelInvitesRequestTypedDict(TypedDict):
    channel_id: str


class ListChannelInvitesRequest(BaseModel):
    channel_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


ListChannelInvitesResponseBodyTypedDict = Union[
    GroupDMInviteResponseTypedDict,
    FriendInviteResponseTypedDict,
    GuildInviteResponseTypedDict,
]


ListChannelInvitesResponseBody = Union[
    GroupDMInviteResponse, FriendInviteResponse, GuildInviteResponse
]
