"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .soundboardsoundresponse import (
    SoundboardSoundResponse,
    SoundboardSoundResponseTypedDict,
)
from discord_sdk.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class ListGuildSoundboardSoundsResponseTypedDict(TypedDict):
    items: List[SoundboardSoundResponseTypedDict]


class ListGuildSoundboardSoundsResponse(BaseModel):
    items: List[SoundboardSoundResponse]
