"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from discord_sdk.types import BaseModel
from typing_extensions import TypedDict


class MessageEmbedFieldResponseTypedDict(TypedDict):
    name: str
    value: str
    inline: bool


class MessageEmbedFieldResponse(BaseModel):
    name: str

    value: str

    inline: bool
