"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .messagereactioncountdetailsresponse import (
    MessageReactionCountDetailsResponse,
    MessageReactionCountDetailsResponseTypedDict,
)
from .messagereactionemojiresponse import (
    MessageReactionEmojiResponse,
    MessageReactionEmojiResponseTypedDict,
)
from discord_sdk.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class MessageReactionResponseTypedDict(TypedDict):
    emoji: MessageReactionEmojiResponseTypedDict
    count: int
    count_details: MessageReactionCountDetailsResponseTypedDict
    burst_colors: List[str]
    me_burst: bool
    me: bool


class MessageReactionResponse(BaseModel):
    emoji: MessageReactionEmojiResponse

    count: int

    count_details: MessageReactionCountDetailsResponse

    burst_colors: List[str]

    me_burst: bool

    me: bool
