"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .messagecomponentbuttonresponse import (
    MessageComponentButtonResponse,
    MessageComponentButtonResponseTypedDict,
)
from .messagecomponentchannelselectresponse import (
    MessageComponentChannelSelectResponse,
    MessageComponentChannelSelectResponseTypedDict,
)
from .messagecomponentinputtextresponse import (
    MessageComponentInputTextResponse,
    MessageComponentInputTextResponseTypedDict,
)
from .messagecomponentmentionableselectresponse import (
    MessageComponentMentionableSelectResponse,
    MessageComponentMentionableSelectResponseTypedDict,
)
from .messagecomponentroleselectresponse import (
    MessageComponentRoleSelectResponse,
    MessageComponentRoleSelectResponseTypedDict,
)
from .messagecomponentstringselectresponse import (
    MessageComponentStringSelectResponse,
    MessageComponentStringSelectResponseTypedDict,
)
from .messagecomponentuserselectresponse import (
    MessageComponentUserSelectResponse,
    MessageComponentUserSelectResponseTypedDict,
)
from discord_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from discord_sdk.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import List, Literal, Union
from typing_extensions import Annotated, NotRequired, TypedDict


ComponentsTypedDict = Union[
    MessageComponentMentionableSelectResponseTypedDict,
    MessageComponentRoleSelectResponseTypedDict,
    MessageComponentStringSelectResponseTypedDict,
    MessageComponentUserSelectResponseTypedDict,
    MessageComponentButtonResponseTypedDict,
    MessageComponentChannelSelectResponseTypedDict,
    MessageComponentInputTextResponseTypedDict,
]


Components = Union[
    MessageComponentMentionableSelectResponse,
    MessageComponentRoleSelectResponse,
    MessageComponentStringSelectResponse,
    MessageComponentUserSelectResponse,
    MessageComponentButtonResponse,
    MessageComponentChannelSelectResponse,
    MessageComponentInputTextResponse,
]


class MessageComponentActionRowResponseTypedDict(TypedDict):
    id: int
    type: Literal[1]
    components: NotRequired[Nullable[List[ComponentsTypedDict]]]


class MessageComponentActionRowResponse(BaseModel):
    id: int

    TYPE: Annotated[
        Annotated[Literal[1], AfterValidator(validate_const(1))],
        pydantic.Field(alias="type"),
    ] = 1

    components: OptionalNullable[List[Components]] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["components"]
        nullable_fields = ["components"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in self.model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
