"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from discord_sdk.types import BaseModel
from typing_extensions import TypedDict


class MessageRoleSubscriptionDataResponseTypedDict(TypedDict):
    role_subscription_listing_id: str
    tier_name: str
    total_months_subscribed: int
    is_renewal: bool


class MessageRoleSubscriptionDataResponse(BaseModel):
    role_subscription_listing_id: str

    tier_name: str

    total_months_subscribed: int

    is_renewal: bool
