"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .applicationcommandinteractionmetadataresponse import (
    ApplicationCommandInteractionMetadataResponse,
    ApplicationCommandInteractionMetadataResponseTypedDict,
)
from .messagecomponentinteractionmetadataresponse import (
    MessageComponentInteractionMetadataResponse,
    MessageComponentInteractionMetadataResponseTypedDict,
)
from .userresponse import UserResponse, UserResponseTypedDict
from discord_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from discord_sdk.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Dict, Literal, Union
from typing_extensions import Annotated, NotRequired, TypedDict


TriggeringInteractionMetadataTypedDict = Union[
    MessageComponentInteractionMetadataResponseTypedDict,
    ApplicationCommandInteractionMetadataResponseTypedDict,
]


TriggeringInteractionMetadata = Union[
    MessageComponentInteractionMetadataResponse,
    ApplicationCommandInteractionMetadataResponse,
]


class ModalSubmitInteractionMetadataResponseTypedDict(TypedDict):
    id: str
    authorizing_integration_owners: Dict[str, str]
    triggering_interaction_metadata: TriggeringInteractionMetadataTypedDict
    type: Literal[1]
    user: NotRequired[Nullable[UserResponseTypedDict]]
    original_response_message_id: NotRequired[Nullable[str]]


class ModalSubmitInteractionMetadataResponse(BaseModel):
    id: str

    authorizing_integration_owners: Dict[str, str]

    triggering_interaction_metadata: TriggeringInteractionMetadata

    TYPE: Annotated[
        Annotated[Literal[1], AfterValidator(validate_const(1))],
        pydantic.Field(alias="type"),
    ] = 1

    user: OptionalNullable[UserResponse] = UNSET

    original_response_message_id: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["user", "original_response_message_id"]
        nullable_fields = ["user", "original_response_message_id"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in self.model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
