"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .applicationcommandpermission import (
    ApplicationCommandPermission,
    ApplicationCommandPermissionTypedDict,
)
from discord_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from discord_sdk.utils import (
    FieldMetadata,
    PathParamMetadata,
    RequestMetadata,
    SecurityMetadata,
)
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class SetGuildApplicationCommandPermissionsSecurityTypedDict(TypedDict):
    bot_token: NotRequired[str]


class SetGuildApplicationCommandPermissionsSecurity(BaseModel):
    bot_token: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="apiKey",
                sub_type="header",
                field_name="Authorization",
            )
        ),
    ] = None


class SetGuildApplicationCommandPermissionsRequestBodyTypedDict(TypedDict):
    permissions: NotRequired[Nullable[List[ApplicationCommandPermissionTypedDict]]]


class SetGuildApplicationCommandPermissionsRequestBody(BaseModel):
    permissions: OptionalNullable[List[ApplicationCommandPermission]] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["permissions"]
        nullable_fields = ["permissions"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in self.model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m


class SetGuildApplicationCommandPermissionsRequestTypedDict(TypedDict):
    application_id: str
    guild_id: str
    command_id: str
    request_body: SetGuildApplicationCommandPermissionsRequestBodyTypedDict


class SetGuildApplicationCommandPermissionsRequest(BaseModel):
    application_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    guild_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    command_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    request_body: Annotated[
        SetGuildApplicationCommandPermissionsRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
