"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from discord_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from discord_sdk.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, NotRequired, TypedDict


class ThreadMetadataResponseTypedDict(TypedDict):
    archived: bool
    locked: bool
    archive_timestamp: NotRequired[Nullable[datetime]]
    auto_archive_duration: Literal[60]
    create_timestamp: NotRequired[Nullable[datetime]]
    invitable: NotRequired[Nullable[bool]]


class ThreadMetadataResponse(BaseModel):
    archived: bool

    locked: bool

    archive_timestamp: OptionalNullable[datetime] = UNSET

    AUTO_ARCHIVE_DURATION: Annotated[
        Annotated[Literal[60], AfterValidator(validate_const(60))],
        pydantic.Field(alias="auto_archive_duration"),
    ] = 60

    create_timestamp: OptionalNullable[datetime] = UNSET

    invitable: OptionalNullable[bool] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["archive_timestamp", "create_timestamp", "invitable"]
        nullable_fields = ["archive_timestamp", "create_timestamp", "invitable"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in self.model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
