"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .applicationformpartial import (
    ApplicationFormPartial,
    ApplicationFormPartialTypedDict,
)
from discord_sdk.types import BaseModel
from discord_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class UpdateApplicationRequestTypedDict(TypedDict):
    application_id: str
    application_form_partial: ApplicationFormPartialTypedDict


class UpdateApplicationRequest(BaseModel):
    application_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    application_form_partial: Annotated[
        ApplicationFormPartial,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
