"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .externalscheduledeventpatchrequestpartial import (
    ExternalScheduledEventPatchRequestPartial,
    ExternalScheduledEventPatchRequestPartialTypedDict,
)
from .externalscheduledeventresponse import (
    ExternalScheduledEventResponse,
    ExternalScheduledEventResponseTypedDict,
)
from .stagescheduledeventpatchrequestpartial import (
    StageScheduledEventPatchRequestPartial,
    StageScheduledEventPatchRequestPartialTypedDict,
)
from .stagescheduledeventresponse import (
    StageScheduledEventResponse,
    StageScheduledEventResponseTypedDict,
)
from .voicescheduledeventpatchrequestpartial import (
    VoiceScheduledEventPatchRequestPartial,
    VoiceScheduledEventPatchRequestPartialTypedDict,
)
from .voicescheduledeventresponse import (
    VoiceScheduledEventResponse,
    VoiceScheduledEventResponseTypedDict,
)
from discord_sdk.types import BaseModel
from discord_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing import Union
from typing_extensions import Annotated, TypedDict


UpdateGuildScheduledEventRequestBodyTypedDict = Union[
    ExternalScheduledEventPatchRequestPartialTypedDict,
    StageScheduledEventPatchRequestPartialTypedDict,
    VoiceScheduledEventPatchRequestPartialTypedDict,
]


UpdateGuildScheduledEventRequestBody = Union[
    ExternalScheduledEventPatchRequestPartial,
    StageScheduledEventPatchRequestPartial,
    VoiceScheduledEventPatchRequestPartial,
]


class UpdateGuildScheduledEventRequestTypedDict(TypedDict):
    guild_id: str
    guild_scheduled_event_id: str
    request_body: UpdateGuildScheduledEventRequestBodyTypedDict


class UpdateGuildScheduledEventRequest(BaseModel):
    guild_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    guild_scheduled_event_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    request_body: Annotated[
        UpdateGuildScheduledEventRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


UpdateGuildScheduledEventResponseBodyTypedDict = Union[
    ExternalScheduledEventResponseTypedDict,
    StageScheduledEventResponseTypedDict,
    VoiceScheduledEventResponseTypedDict,
]
r"""200 response for update_guild_scheduled_event"""


UpdateGuildScheduledEventResponseBody = Union[
    ExternalScheduledEventResponse,
    StageScheduledEventResponse,
    VoiceScheduledEventResponse,
]
r"""200 response for update_guild_scheduled_event"""
