"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .defaultkeywordlistupsertrequestpartial import (
    DefaultKeywordListUpsertRequestPartial,
    DefaultKeywordListUpsertRequestPartialTypedDict,
)
from .defaultkeywordruleresponse import (
    DefaultKeywordRuleResponse,
    DefaultKeywordRuleResponseTypedDict,
)
from .keywordruleresponse import KeywordRuleResponse, KeywordRuleResponseTypedDict
from .keywordupsertrequestpartial import (
    KeywordUpsertRequestPartial,
    KeywordUpsertRequestPartialTypedDict,
)
from .mentionspamruleresponse import (
    MentionSpamRuleResponse,
    MentionSpamRuleResponseTypedDict,
)
from .mentionspamupsertrequestpartial import (
    MentionSpamUpsertRequestPartial,
    MentionSpamUpsertRequestPartialTypedDict,
)
from .mlspamruleresponse import MLSpamRuleResponse, MLSpamRuleResponseTypedDict
from .mlspamupsertrequestpartial import (
    MLSpamUpsertRequestPartial,
    MLSpamUpsertRequestPartialTypedDict,
)
from .spamlinkruleresponse import SpamLinkRuleResponse, SpamLinkRuleResponseTypedDict
from discord_sdk.types import BaseModel
from discord_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing import Union
from typing_extensions import Annotated, TypedDict


UpdateAutoModerationRuleRequestBodyTypedDict = Union[
    DefaultKeywordListUpsertRequestPartialTypedDict,
    KeywordUpsertRequestPartialTypedDict,
    MLSpamUpsertRequestPartialTypedDict,
    MentionSpamUpsertRequestPartialTypedDict,
]


UpdateAutoModerationRuleRequestBody = Union[
    DefaultKeywordListUpsertRequestPartial,
    KeywordUpsertRequestPartial,
    MLSpamUpsertRequestPartial,
    MentionSpamUpsertRequestPartial,
]


class UpdateAutoModerationRuleRequestTypedDict(TypedDict):
    guild_id: str
    rule_id: str
    request_body: UpdateAutoModerationRuleRequestBodyTypedDict


class UpdateAutoModerationRuleRequest(BaseModel):
    guild_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    rule_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    request_body: Annotated[
        UpdateAutoModerationRuleRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


UpdateAutoModerationRuleResponseBodyTypedDict = Union[
    DefaultKeywordRuleResponseTypedDict,
    KeywordRuleResponseTypedDict,
    MLSpamRuleResponseTypedDict,
    MentionSpamRuleResponseTypedDict,
    SpamLinkRuleResponseTypedDict,
]
r"""200 response for update_auto_moderation_rule"""


UpdateAutoModerationRuleResponseBody = Union[
    DefaultKeywordRuleResponse,
    KeywordRuleResponse,
    MLSpamRuleResponse,
    MentionSpamRuleResponse,
    SpamLinkRuleResponse,
]
r"""200 response for update_auto_moderation_rule"""
