"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .messageeditrequestpartial import (
    MessageEditRequestPartial,
    MessageEditRequestPartialTypedDict,
)
from discord_sdk.types import BaseModel
from discord_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class UpdateMessageFormRequestTypedDict(TypedDict):
    channel_id: str
    message_id: str
    message_edit_request_partial: MessageEditRequestPartialTypedDict


class UpdateMessageFormRequest(BaseModel):
    channel_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    message_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    message_edit_request_partial: Annotated[
        MessageEditRequestPartial,
        FieldMetadata(
            request=RequestMetadata(media_type="application/x-www-form-urlencoded")
        ),
    ]
