"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from discord_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from discord_sdk.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import List, Literal
from typing_extensions import Annotated, NotRequired, TypedDict


class UpdateThreadRequestPartialTypedDict(TypedDict):
    name: NotRequired[Nullable[str]]
    archived: NotRequired[Nullable[bool]]
    locked: NotRequired[Nullable[bool]]
    invitable: NotRequired[Nullable[bool]]
    auto_archive_duration: Nullable[Literal[60]]
    rate_limit_per_user: NotRequired[Nullable[int]]
    flags: NotRequired[Nullable[int]]
    applied_tags: NotRequired[Nullable[List[str]]]
    bitrate: NotRequired[Nullable[int]]
    user_limit: NotRequired[Nullable[int]]
    rtc_region: NotRequired[Nullable[str]]
    video_quality_mode: Nullable[Literal[1]]


class UpdateThreadRequestPartial(BaseModel):
    name: OptionalNullable[str] = UNSET

    archived: OptionalNullable[bool] = UNSET

    locked: OptionalNullable[bool] = UNSET

    invitable: OptionalNullable[bool] = UNSET

    AUTO_ARCHIVE_DURATION: Annotated[
        Annotated[OptionalNullable[Literal[60]], AfterValidator(validate_const(60))],
        pydantic.Field(alias="auto_archive_duration"),
    ] = 60

    rate_limit_per_user: OptionalNullable[int] = UNSET

    flags: OptionalNullable[int] = UNSET

    applied_tags: OptionalNullable[List[str]] = UNSET

    bitrate: OptionalNullable[int] = UNSET

    user_limit: OptionalNullable[int] = UNSET

    rtc_region: OptionalNullable[str] = UNSET

    VIDEO_QUALITY_MODE: Annotated[
        Annotated[OptionalNullable[Literal[1]], AfterValidator(validate_const(1))],
        pydantic.Field(alias="video_quality_mode"),
    ] = 1

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "name",
            "archived",
            "locked",
            "invitable",
            "auto_archive_duration",
            "rate_limit_per_user",
            "flags",
            "applied_tags",
            "bitrate",
            "user_limit",
            "rtc_region",
            "video_quality_mode",
        ]
        nullable_fields = [
            "name",
            "archived",
            "locked",
            "invitable",
            "auto_archive_duration",
            "rate_limit_per_user",
            "flags",
            "applied_tags",
            "bitrate",
            "user_limit",
            "rtc_region",
            "video_quality_mode",
        ]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in self.model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
