"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from discord_sdk.types import BaseModel
from typing_extensions import TypedDict


class VoiceRegionResponseTypedDict(TypedDict):
    id: str
    name: str
    custom: bool
    deprecated: bool
    optimal: bool


class VoiceRegionResponse(BaseModel):
    id: str

    name: str

    custom: bool

    deprecated: bool

    optimal: bool
