"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from discord_sdk import models, utils
from discord_sdk._hooks import HookContext
from discord_sdk.types import Nullable, OptionalNullable, UNSET
from discord_sdk.utils import get_security_from_env
from typing import Any, List, Optional, Union


class Commands(BaseSDK):
    def list_permissions(
        self,
        *,
        security: Union[
            models.ListGuildApplicationCommandPermissionsSecurity,
            models.ListGuildApplicationCommandPermissionsSecurityTypedDict,
        ],
        application_id: str,
        guild_id: str,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
    ) -> List[models.CommandPermissionsResponse]:
        r"""
        :param security:
        :param application_id:
        :param guild_id:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url

        request = models.ListGuildApplicationCommandPermissionsRequest(
            application_id=application_id,
            guild_id=guild_id,
        )

        req = self.build_request(
            method="GET",
            path="/applications/{application_id}/guilds/{guild_id}/commands/permissions",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            security=utils.get_pydantic_model(
                security, models.ListGuildApplicationCommandPermissionsSecurity
            ),
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                operation_id="list_guild_application_command_permissions",
                oauth2_scopes=["applications.commands.permissions.update"],
                security_source=get_security_from_env(security, models.Security),
            ),
            request=req,
            error_status_codes=["4XX", "5XX"],
            retry_config=retry_config,
        )

        data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return utils.unmarshal_json(
                http_res.text, List[models.CommandPermissionsResponse]
            )
        if utils.match_response(http_res, "4XX", "application/json"):
            data = utils.unmarshal_json(http_res.text, models.ErrorResponseData)
            raise models.ErrorResponse(data=data)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models.SDKError(
                "API error occurred", http_res.status_code, http_res_text, http_res
            )

        content_type = http_res.headers.get("Content-Type")
        http_res_text = utils.stream_to_text(http_res)
        raise models.SDKError(
            f"Unexpected response received (code: {http_res.status_code}, type: {content_type})",
            http_res.status_code,
            http_res_text,
            http_res,
        )

    async def list_permissions_async(
        self,
        *,
        security: Union[
            models.ListGuildApplicationCommandPermissionsSecurity,
            models.ListGuildApplicationCommandPermissionsSecurityTypedDict,
        ],
        application_id: str,
        guild_id: str,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
    ) -> List[models.CommandPermissionsResponse]:
        r"""
        :param security:
        :param application_id:
        :param guild_id:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url

        request = models.ListGuildApplicationCommandPermissionsRequest(
            application_id=application_id,
            guild_id=guild_id,
        )

        req = self.build_request_async(
            method="GET",
            path="/applications/{application_id}/guilds/{guild_id}/commands/permissions",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            security=utils.get_pydantic_model(
                security, models.ListGuildApplicationCommandPermissionsSecurity
            ),
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                operation_id="list_guild_application_command_permissions",
                oauth2_scopes=["applications.commands.permissions.update"],
                security_source=get_security_from_env(security, models.Security),
            ),
            request=req,
            error_status_codes=["4XX", "5XX"],
            retry_config=retry_config,
        )

        data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return utils.unmarshal_json(
                http_res.text, List[models.CommandPermissionsResponse]
            )
        if utils.match_response(http_res, "4XX", "application/json"):
            data = utils.unmarshal_json(http_res.text, models.ErrorResponseData)
            raise models.ErrorResponse(data=data)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models.SDKError(
                "API error occurred", http_res.status_code, http_res_text, http_res
            )

        content_type = http_res.headers.get("Content-Type")
        http_res_text = await utils.stream_to_text_async(http_res)
        raise models.SDKError(
            f"Unexpected response received (code: {http_res.status_code}, type: {content_type})",
            http_res.status_code,
            http_res_text,
            http_res,
        )

    def set_permission(
        self,
        *,
        security: Union[
            models.SetGuildApplicationCommandPermissionsSecurity,
            models.SetGuildApplicationCommandPermissionsSecurityTypedDict,
        ],
        application_id: str,
        guild_id: str,
        command_id: str,
        request_body: Union[
            models.SetGuildApplicationCommandPermissionsRequestBody,
            models.SetGuildApplicationCommandPermissionsRequestBodyTypedDict,
        ],
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
    ) -> models.CommandPermissionsResponse:
        r"""
        :param security:
        :param application_id:
        :param guild_id:
        :param command_id:
        :param request_body:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url

        request = models.SetGuildApplicationCommandPermissionsRequest(
            application_id=application_id,
            guild_id=guild_id,
            command_id=command_id,
            request_body=utils.get_pydantic_model(
                request_body, models.SetGuildApplicationCommandPermissionsRequestBody
            ),
        )

        req = self.build_request(
            method="PUT",
            path="/applications/{application_id}/guilds/{guild_id}/commands/{command_id}/permissions",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            security=utils.get_pydantic_model(
                security, models.SetGuildApplicationCommandPermissionsSecurity
            ),
            get_serialized_body=lambda: utils.serialize_request_body(
                request.request_body,
                False,
                False,
                "json",
                models.SetGuildApplicationCommandPermissionsRequestBody,
            ),
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                operation_id="set_guild_application_command_permissions",
                oauth2_scopes=["applications.commands.permissions.update"],
                security_source=get_security_from_env(security, models.Security),
            ),
            request=req,
            error_status_codes=["4XX", "5XX"],
            retry_config=retry_config,
        )

        data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return utils.unmarshal_json(
                http_res.text, models.CommandPermissionsResponse
            )
        if utils.match_response(http_res, "4XX", "application/json"):
            data = utils.unmarshal_json(http_res.text, models.ErrorResponseData)
            raise models.ErrorResponse(data=data)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models.SDKError(
                "API error occurred", http_res.status_code, http_res_text, http_res
            )

        content_type = http_res.headers.get("Content-Type")
        http_res_text = utils.stream_to_text(http_res)
        raise models.SDKError(
            f"Unexpected response received (code: {http_res.status_code}, type: {content_type})",
            http_res.status_code,
            http_res_text,
            http_res,
        )

    async def set_permission_async(
        self,
        *,
        security: Union[
            models.SetGuildApplicationCommandPermissionsSecurity,
            models.SetGuildApplicationCommandPermissionsSecurityTypedDict,
        ],
        application_id: str,
        guild_id: str,
        command_id: str,
        request_body: Union[
            models.SetGuildApplicationCommandPermissionsRequestBody,
            models.SetGuildApplicationCommandPermissionsRequestBodyTypedDict,
        ],
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
    ) -> models.CommandPermissionsResponse:
        r"""
        :param security:
        :param application_id:
        :param guild_id:
        :param command_id:
        :param request_body:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url

        request = models.SetGuildApplicationCommandPermissionsRequest(
            application_id=application_id,
            guild_id=guild_id,
            command_id=command_id,
            request_body=utils.get_pydantic_model(
                request_body, models.SetGuildApplicationCommandPermissionsRequestBody
            ),
        )

        req = self.build_request_async(
            method="PUT",
            path="/applications/{application_id}/guilds/{guild_id}/commands/{command_id}/permissions",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            security=utils.get_pydantic_model(
                security, models.SetGuildApplicationCommandPermissionsSecurity
            ),
            get_serialized_body=lambda: utils.serialize_request_body(
                request.request_body,
                False,
                False,
                "json",
                models.SetGuildApplicationCommandPermissionsRequestBody,
            ),
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                operation_id="set_guild_application_command_permissions",
                oauth2_scopes=["applications.commands.permissions.update"],
                security_source=get_security_from_env(security, models.Security),
            ),
            request=req,
            error_status_codes=["4XX", "5XX"],
            retry_config=retry_config,
        )

        data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return utils.unmarshal_json(
                http_res.text, models.CommandPermissionsResponse
            )
        if utils.match_response(http_res, "4XX", "application/json"):
            data = utils.unmarshal_json(http_res.text, models.ErrorResponseData)
            raise models.ErrorResponse(data=data)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models.SDKError(
                "API error occurred", http_res.status_code, http_res_text, http_res
            )

        content_type = http_res.headers.get("Content-Type")
        http_res_text = await utils.stream_to_text_async(http_res)
        raise models.SDKError(
            f"Unexpected response received (code: {http_res.status_code}, type: {content_type})",
            http_res.status_code,
            http_res_text,
            http_res,
        )

    def bulk_set(
        self,
        *,
        security: Union[
            models.BulkSetGuildApplicationCommandsSecurity,
            models.BulkSetGuildApplicationCommandsSecurityTypedDict,
        ],
        application_id: str,
        guild_id: str,
        request_body: Nullable[
            Union[
                List[models.ApplicationCommandUpdateRequest],
                List[models.ApplicationCommandUpdateRequestTypedDict],
            ]
        ],
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
    ) -> List[models.ApplicationCommandResponse]:
        r"""
        :param security:
        :param application_id:
        :param guild_id:
        :param request_body:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url

        request = models.BulkSetGuildApplicationCommandsRequest(
            application_id=application_id,
            guild_id=guild_id,
            request_body=utils.get_pydantic_model(
                request_body, Nullable[List[models.ApplicationCommandUpdateRequest]]
            ),
        )

        req = self.build_request(
            method="PUT",
            path="/applications/{application_id}/guilds/{guild_id}/commands",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            security=utils.get_pydantic_model(
                security, models.BulkSetGuildApplicationCommandsSecurity
            ),
            get_serialized_body=lambda: utils.serialize_request_body(
                request.request_body,
                True,
                False,
                "json",
                Nullable[List[models.ApplicationCommandUpdateRequest]],
            ),
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                operation_id="bulk_set_guild_application_commands",
                oauth2_scopes=["applications.commands.update"],
                security_source=get_security_from_env(security, models.Security),
            ),
            request=req,
            error_status_codes=["4XX", "5XX"],
            retry_config=retry_config,
        )

        data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return utils.unmarshal_json(
                http_res.text, List[models.ApplicationCommandResponse]
            )
        if utils.match_response(http_res, "4XX", "application/json"):
            data = utils.unmarshal_json(http_res.text, models.ErrorResponseData)
            raise models.ErrorResponse(data=data)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models.SDKError(
                "API error occurred", http_res.status_code, http_res_text, http_res
            )

        content_type = http_res.headers.get("Content-Type")
        http_res_text = utils.stream_to_text(http_res)
        raise models.SDKError(
            f"Unexpected response received (code: {http_res.status_code}, type: {content_type})",
            http_res.status_code,
            http_res_text,
            http_res,
        )

    async def bulk_set_async(
        self,
        *,
        security: Union[
            models.BulkSetGuildApplicationCommandsSecurity,
            models.BulkSetGuildApplicationCommandsSecurityTypedDict,
        ],
        application_id: str,
        guild_id: str,
        request_body: Nullable[
            Union[
                List[models.ApplicationCommandUpdateRequest],
                List[models.ApplicationCommandUpdateRequestTypedDict],
            ]
        ],
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
    ) -> List[models.ApplicationCommandResponse]:
        r"""
        :param security:
        :param application_id:
        :param guild_id:
        :param request_body:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url

        request = models.BulkSetGuildApplicationCommandsRequest(
            application_id=application_id,
            guild_id=guild_id,
            request_body=utils.get_pydantic_model(
                request_body, Nullable[List[models.ApplicationCommandUpdateRequest]]
            ),
        )

        req = self.build_request_async(
            method="PUT",
            path="/applications/{application_id}/guilds/{guild_id}/commands",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            security=utils.get_pydantic_model(
                security, models.BulkSetGuildApplicationCommandsSecurity
            ),
            get_serialized_body=lambda: utils.serialize_request_body(
                request.request_body,
                True,
                False,
                "json",
                Nullable[List[models.ApplicationCommandUpdateRequest]],
            ),
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                operation_id="bulk_set_guild_application_commands",
                oauth2_scopes=["applications.commands.update"],
                security_source=get_security_from_env(security, models.Security),
            ),
            request=req,
            error_status_codes=["4XX", "5XX"],
            retry_config=retry_config,
        )

        data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return utils.unmarshal_json(
                http_res.text, List[models.ApplicationCommandResponse]
            )
        if utils.match_response(http_res, "4XX", "application/json"):
            data = utils.unmarshal_json(http_res.text, models.ErrorResponseData)
            raise models.ErrorResponse(data=data)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models.SDKError(
                "API error occurred", http_res.status_code, http_res_text, http_res
            )

        content_type = http_res.headers.get("Content-Type")
        http_res_text = await utils.stream_to_text_async(http_res)
        raise models.SDKError(
            f"Unexpected response received (code: {http_res.status_code}, type: {content_type})",
            http_res.status_code,
            http_res_text,
            http_res,
        )
