"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from discord_sdk import models, utils
from discord_sdk._hooks import HookContext
from discord_sdk.types import BaseModel, OptionalNullable, UNSET
from discord_sdk.utils import get_security_from_env
from typing import Any, Optional, Union, cast


class WebhookMessages(BaseSDK):
    def get_original(
        self,
        *,
        webhook_id: str,
        webhook_token: str,
        thread_id: Optional[str] = None,
        security: Optional[
            Union[
                models.GetOriginalWebhookMessageSecurity,
                models.GetOriginalWebhookMessageSecurityTypedDict,
            ]
        ] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
    ) -> models.MessageResponse:
        r"""
        :param webhook_id:
        :param webhook_token:
        :param thread_id:
        :param security:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url

        request = models.GetOriginalWebhookMessageRequest(
            webhook_id=webhook_id,
            webhook_token=webhook_token,
            thread_id=thread_id,
        )

        req = self.build_request(
            method="GET",
            path="/webhooks/{webhook_id}/{webhook_token}/messages/@original",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            security=utils.get_pydantic_model(
                security, Optional[models.GetOriginalWebhookMessageSecurity]
            ),
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                operation_id="get_original_webhook_message",
                oauth2_scopes=[],
                security_source=get_security_from_env(security, models.Security),
            ),
            request=req,
            error_status_codes=["4XX", "5XX"],
            retry_config=retry_config,
        )

        data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return utils.unmarshal_json(http_res.text, models.MessageResponse)
        if utils.match_response(http_res, "4XX", "application/json"):
            data = utils.unmarshal_json(http_res.text, models.ErrorResponseData)
            raise models.ErrorResponse(data=data)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models.SDKError(
                "API error occurred", http_res.status_code, http_res_text, http_res
            )

        content_type = http_res.headers.get("Content-Type")
        http_res_text = utils.stream_to_text(http_res)
        raise models.SDKError(
            f"Unexpected response received (code: {http_res.status_code}, type: {content_type})",
            http_res.status_code,
            http_res_text,
            http_res,
        )

    async def get_original_async(
        self,
        *,
        webhook_id: str,
        webhook_token: str,
        thread_id: Optional[str] = None,
        security: Optional[
            Union[
                models.GetOriginalWebhookMessageSecurity,
                models.GetOriginalWebhookMessageSecurityTypedDict,
            ]
        ] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
    ) -> models.MessageResponse:
        r"""
        :param webhook_id:
        :param webhook_token:
        :param thread_id:
        :param security:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url

        request = models.GetOriginalWebhookMessageRequest(
            webhook_id=webhook_id,
            webhook_token=webhook_token,
            thread_id=thread_id,
        )

        req = self.build_request_async(
            method="GET",
            path="/webhooks/{webhook_id}/{webhook_token}/messages/@original",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            security=utils.get_pydantic_model(
                security, Optional[models.GetOriginalWebhookMessageSecurity]
            ),
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                operation_id="get_original_webhook_message",
                oauth2_scopes=[],
                security_source=get_security_from_env(security, models.Security),
            ),
            request=req,
            error_status_codes=["4XX", "5XX"],
            retry_config=retry_config,
        )

        data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return utils.unmarshal_json(http_res.text, models.MessageResponse)
        if utils.match_response(http_res, "4XX", "application/json"):
            data = utils.unmarshal_json(http_res.text, models.ErrorResponseData)
            raise models.ErrorResponse(data=data)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models.SDKError(
                "API error occurred", http_res.status_code, http_res_text, http_res
            )

        content_type = http_res.headers.get("Content-Type")
        http_res_text = await utils.stream_to_text_async(http_res)
        raise models.SDKError(
            f"Unexpected response received (code: {http_res.status_code}, type: {content_type})",
            http_res.status_code,
            http_res_text,
            http_res,
        )

    def update_original_json(
        self,
        *,
        webhook_id: str,
        webhook_token: str,
        incoming_webhook_update_request_partial: Union[
            models.IncomingWebhookUpdateRequestPartial,
            models.IncomingWebhookUpdateRequestPartialTypedDict,
        ],
        thread_id: Optional[str] = None,
        security: Optional[
            Union[
                models.UpdateOriginalWebhookMessageJSONSecurity,
                models.UpdateOriginalWebhookMessageJSONSecurityTypedDict,
            ]
        ] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
    ) -> models.MessageResponse:
        r"""
        :param webhook_id:
        :param webhook_token:
        :param incoming_webhook_update_request_partial:
        :param thread_id:
        :param security:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url

        request = models.UpdateOriginalWebhookMessageJSONRequest(
            webhook_id=webhook_id,
            webhook_token=webhook_token,
            thread_id=thread_id,
            incoming_webhook_update_request_partial=utils.get_pydantic_model(
                incoming_webhook_update_request_partial,
                models.IncomingWebhookUpdateRequestPartial,
            ),
        )

        req = self.build_request(
            method="PATCH",
            path="/webhooks/{webhook_id}/{webhook_token}/messages/@original",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            security=utils.get_pydantic_model(
                security, Optional[models.UpdateOriginalWebhookMessageJSONSecurity]
            ),
            get_serialized_body=lambda: utils.serialize_request_body(
                request.incoming_webhook_update_request_partial,
                False,
                False,
                "json",
                models.IncomingWebhookUpdateRequestPartial,
            ),
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                operation_id="update_original_webhook_message_json",
                oauth2_scopes=[],
                security_source=get_security_from_env(security, models.Security),
            ),
            request=req,
            error_status_codes=["4XX", "5XX"],
            retry_config=retry_config,
        )

        data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return utils.unmarshal_json(http_res.text, models.MessageResponse)
        if utils.match_response(http_res, "4XX", "application/json"):
            data = utils.unmarshal_json(http_res.text, models.ErrorResponseData)
            raise models.ErrorResponse(data=data)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models.SDKError(
                "API error occurred", http_res.status_code, http_res_text, http_res
            )

        content_type = http_res.headers.get("Content-Type")
        http_res_text = utils.stream_to_text(http_res)
        raise models.SDKError(
            f"Unexpected response received (code: {http_res.status_code}, type: {content_type})",
            http_res.status_code,
            http_res_text,
            http_res,
        )

    async def update_original_json_async(
        self,
        *,
        webhook_id: str,
        webhook_token: str,
        incoming_webhook_update_request_partial: Union[
            models.IncomingWebhookUpdateRequestPartial,
            models.IncomingWebhookUpdateRequestPartialTypedDict,
        ],
        thread_id: Optional[str] = None,
        security: Optional[
            Union[
                models.UpdateOriginalWebhookMessageJSONSecurity,
                models.UpdateOriginalWebhookMessageJSONSecurityTypedDict,
            ]
        ] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
    ) -> models.MessageResponse:
        r"""
        :param webhook_id:
        :param webhook_token:
        :param incoming_webhook_update_request_partial:
        :param thread_id:
        :param security:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url

        request = models.UpdateOriginalWebhookMessageJSONRequest(
            webhook_id=webhook_id,
            webhook_token=webhook_token,
            thread_id=thread_id,
            incoming_webhook_update_request_partial=utils.get_pydantic_model(
                incoming_webhook_update_request_partial,
                models.IncomingWebhookUpdateRequestPartial,
            ),
        )

        req = self.build_request_async(
            method="PATCH",
            path="/webhooks/{webhook_id}/{webhook_token}/messages/@original",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            security=utils.get_pydantic_model(
                security, Optional[models.UpdateOriginalWebhookMessageJSONSecurity]
            ),
            get_serialized_body=lambda: utils.serialize_request_body(
                request.incoming_webhook_update_request_partial,
                False,
                False,
                "json",
                models.IncomingWebhookUpdateRequestPartial,
            ),
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                operation_id="update_original_webhook_message_json",
                oauth2_scopes=[],
                security_source=get_security_from_env(security, models.Security),
            ),
            request=req,
            error_status_codes=["4XX", "5XX"],
            retry_config=retry_config,
        )

        data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return utils.unmarshal_json(http_res.text, models.MessageResponse)
        if utils.match_response(http_res, "4XX", "application/json"):
            data = utils.unmarshal_json(http_res.text, models.ErrorResponseData)
            raise models.ErrorResponse(data=data)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models.SDKError(
                "API error occurred", http_res.status_code, http_res_text, http_res
            )

        content_type = http_res.headers.get("Content-Type")
        http_res_text = await utils.stream_to_text_async(http_res)
        raise models.SDKError(
            f"Unexpected response received (code: {http_res.status_code}, type: {content_type})",
            http_res.status_code,
            http_res_text,
            http_res,
        )

    def update_original_form(
        self,
        *,
        webhook_id: str,
        webhook_token: str,
        incoming_webhook_update_request_partial: Union[
            models.IncomingWebhookUpdateRequestPartial,
            models.IncomingWebhookUpdateRequestPartialTypedDict,
        ],
        thread_id: Optional[str] = None,
        security: Optional[
            Union[
                models.UpdateOriginalWebhookMessageFormSecurity,
                models.UpdateOriginalWebhookMessageFormSecurityTypedDict,
            ]
        ] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
    ) -> models.MessageResponse:
        r"""
        :param webhook_id:
        :param webhook_token:
        :param incoming_webhook_update_request_partial:
        :param thread_id:
        :param security:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url

        request = models.UpdateOriginalWebhookMessageFormRequest(
            webhook_id=webhook_id,
            webhook_token=webhook_token,
            thread_id=thread_id,
            incoming_webhook_update_request_partial=utils.get_pydantic_model(
                incoming_webhook_update_request_partial,
                models.IncomingWebhookUpdateRequestPartial,
            ),
        )

        req = self.build_request(
            method="PATCH",
            path="/webhooks/{webhook_id}/{webhook_token}/messages/@original",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            security=utils.get_pydantic_model(
                security, Optional[models.UpdateOriginalWebhookMessageFormSecurity]
            ),
            get_serialized_body=lambda: utils.serialize_request_body(
                request.incoming_webhook_update_request_partial,
                False,
                False,
                "form",
                models.IncomingWebhookUpdateRequestPartial,
            ),
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                operation_id="update_original_webhook_message_form",
                oauth2_scopes=[],
                security_source=get_security_from_env(security, models.Security),
            ),
            request=req,
            error_status_codes=["4XX", "5XX"],
            retry_config=retry_config,
        )

        data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return utils.unmarshal_json(http_res.text, models.MessageResponse)
        if utils.match_response(http_res, "4XX", "application/json"):
            data = utils.unmarshal_json(http_res.text, models.ErrorResponseData)
            raise models.ErrorResponse(data=data)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models.SDKError(
                "API error occurred", http_res.status_code, http_res_text, http_res
            )

        content_type = http_res.headers.get("Content-Type")
        http_res_text = utils.stream_to_text(http_res)
        raise models.SDKError(
            f"Unexpected response received (code: {http_res.status_code}, type: {content_type})",
            http_res.status_code,
            http_res_text,
            http_res,
        )

    async def update_original_form_async(
        self,
        *,
        webhook_id: str,
        webhook_token: str,
        incoming_webhook_update_request_partial: Union[
            models.IncomingWebhookUpdateRequestPartial,
            models.IncomingWebhookUpdateRequestPartialTypedDict,
        ],
        thread_id: Optional[str] = None,
        security: Optional[
            Union[
                models.UpdateOriginalWebhookMessageFormSecurity,
                models.UpdateOriginalWebhookMessageFormSecurityTypedDict,
            ]
        ] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
    ) -> models.MessageResponse:
        r"""
        :param webhook_id:
        :param webhook_token:
        :param incoming_webhook_update_request_partial:
        :param thread_id:
        :param security:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url

        request = models.UpdateOriginalWebhookMessageFormRequest(
            webhook_id=webhook_id,
            webhook_token=webhook_token,
            thread_id=thread_id,
            incoming_webhook_update_request_partial=utils.get_pydantic_model(
                incoming_webhook_update_request_partial,
                models.IncomingWebhookUpdateRequestPartial,
            ),
        )

        req = self.build_request_async(
            method="PATCH",
            path="/webhooks/{webhook_id}/{webhook_token}/messages/@original",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            security=utils.get_pydantic_model(
                security, Optional[models.UpdateOriginalWebhookMessageFormSecurity]
            ),
            get_serialized_body=lambda: utils.serialize_request_body(
                request.incoming_webhook_update_request_partial,
                False,
                False,
                "form",
                models.IncomingWebhookUpdateRequestPartial,
            ),
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                operation_id="update_original_webhook_message_form",
                oauth2_scopes=[],
                security_source=get_security_from_env(security, models.Security),
            ),
            request=req,
            error_status_codes=["4XX", "5XX"],
            retry_config=retry_config,
        )

        data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return utils.unmarshal_json(http_res.text, models.MessageResponse)
        if utils.match_response(http_res, "4XX", "application/json"):
            data = utils.unmarshal_json(http_res.text, models.ErrorResponseData)
            raise models.ErrorResponse(data=data)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models.SDKError(
                "API error occurred", http_res.status_code, http_res_text, http_res
            )

        content_type = http_res.headers.get("Content-Type")
        http_res_text = await utils.stream_to_text_async(http_res)
        raise models.SDKError(
            f"Unexpected response received (code: {http_res.status_code}, type: {content_type})",
            http_res.status_code,
            http_res_text,
            http_res,
        )

    def update_original_multipart(
        self,
        *,
        webhook_id: str,
        webhook_token: str,
        request_body: Union[
            models.UpdateOriginalWebhookMessageMultipartRequestBody,
            models.UpdateOriginalWebhookMessageMultipartRequestBodyTypedDict,
        ],
        thread_id: Optional[str] = None,
        security: Optional[
            Union[
                models.UpdateOriginalWebhookMessageMultipartSecurity,
                models.UpdateOriginalWebhookMessageMultipartSecurityTypedDict,
            ]
        ] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
    ) -> models.MessageResponse:
        r"""
        :param webhook_id:
        :param webhook_token:
        :param request_body:
        :param thread_id:
        :param security:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url

        request = models.UpdateOriginalWebhookMessageMultipartRequest(
            webhook_id=webhook_id,
            webhook_token=webhook_token,
            thread_id=thread_id,
            request_body=utils.get_pydantic_model(
                request_body, models.UpdateOriginalWebhookMessageMultipartRequestBody
            ),
        )

        req = self.build_request(
            method="PATCH",
            path="/webhooks/{webhook_id}/{webhook_token}/messages/@original",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            security=utils.get_pydantic_model(
                security, Optional[models.UpdateOriginalWebhookMessageMultipartSecurity]
            ),
            get_serialized_body=lambda: utils.serialize_request_body(
                request.request_body,
                False,
                False,
                "multipart",
                models.UpdateOriginalWebhookMessageMultipartRequestBody,
            ),
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                operation_id="update_original_webhook_message_multipart",
                oauth2_scopes=[],
                security_source=get_security_from_env(security, models.Security),
            ),
            request=req,
            error_status_codes=["4XX", "5XX"],
            retry_config=retry_config,
        )

        data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return utils.unmarshal_json(http_res.text, models.MessageResponse)
        if utils.match_response(http_res, "4XX", "application/json"):
            data = utils.unmarshal_json(http_res.text, models.ErrorResponseData)
            raise models.ErrorResponse(data=data)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models.SDKError(
                "API error occurred", http_res.status_code, http_res_text, http_res
            )

        content_type = http_res.headers.get("Content-Type")
        http_res_text = utils.stream_to_text(http_res)
        raise models.SDKError(
            f"Unexpected response received (code: {http_res.status_code}, type: {content_type})",
            http_res.status_code,
            http_res_text,
            http_res,
        )

    async def update_original_multipart_async(
        self,
        *,
        webhook_id: str,
        webhook_token: str,
        request_body: Union[
            models.UpdateOriginalWebhookMessageMultipartRequestBody,
            models.UpdateOriginalWebhookMessageMultipartRequestBodyTypedDict,
        ],
        thread_id: Optional[str] = None,
        security: Optional[
            Union[
                models.UpdateOriginalWebhookMessageMultipartSecurity,
                models.UpdateOriginalWebhookMessageMultipartSecurityTypedDict,
            ]
        ] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
    ) -> models.MessageResponse:
        r"""
        :param webhook_id:
        :param webhook_token:
        :param request_body:
        :param thread_id:
        :param security:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url

        request = models.UpdateOriginalWebhookMessageMultipartRequest(
            webhook_id=webhook_id,
            webhook_token=webhook_token,
            thread_id=thread_id,
            request_body=utils.get_pydantic_model(
                request_body, models.UpdateOriginalWebhookMessageMultipartRequestBody
            ),
        )

        req = self.build_request_async(
            method="PATCH",
            path="/webhooks/{webhook_id}/{webhook_token}/messages/@original",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            security=utils.get_pydantic_model(
                security, Optional[models.UpdateOriginalWebhookMessageMultipartSecurity]
            ),
            get_serialized_body=lambda: utils.serialize_request_body(
                request.request_body,
                False,
                False,
                "multipart",
                models.UpdateOriginalWebhookMessageMultipartRequestBody,
            ),
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                operation_id="update_original_webhook_message_multipart",
                oauth2_scopes=[],
                security_source=get_security_from_env(security, models.Security),
            ),
            request=req,
            error_status_codes=["4XX", "5XX"],
            retry_config=retry_config,
        )

        data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return utils.unmarshal_json(http_res.text, models.MessageResponse)
        if utils.match_response(http_res, "4XX", "application/json"):
            data = utils.unmarshal_json(http_res.text, models.ErrorResponseData)
            raise models.ErrorResponse(data=data)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models.SDKError(
                "API error occurred", http_res.status_code, http_res_text, http_res
            )

        content_type = http_res.headers.get("Content-Type")
        http_res_text = await utils.stream_to_text_async(http_res)
        raise models.SDKError(
            f"Unexpected response received (code: {http_res.status_code}, type: {content_type})",
            http_res.status_code,
            http_res_text,
            http_res,
        )

    def update_json(
        self,
        *,
        request: Union[
            models.UpdateWebhookMessageJSONRequest,
            models.UpdateWebhookMessageJSONRequestTypedDict,
        ],
        security: Optional[
            Union[
                models.UpdateWebhookMessageJSONSecurity,
                models.UpdateWebhookMessageJSONSecurityTypedDict,
            ]
        ] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
    ) -> models.MessageResponse:
        r"""
        :param request: The request object to send.
        :param security:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url

        if not isinstance(request, BaseModel):
            request = utils.unmarshal(request, models.UpdateWebhookMessageJSONRequest)
        request = cast(models.UpdateWebhookMessageJSONRequest, request)

        req = self.build_request(
            method="PATCH",
            path="/webhooks/{webhook_id}/{webhook_token}/messages/{message_id}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            security=utils.get_pydantic_model(
                security, Optional[models.UpdateWebhookMessageJSONSecurity]
            ),
            get_serialized_body=lambda: utils.serialize_request_body(
                request.incoming_webhook_update_request_partial,
                False,
                False,
                "json",
                models.IncomingWebhookUpdateRequestPartial,
            ),
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                operation_id="update_webhook_message_json",
                oauth2_scopes=[],
                security_source=get_security_from_env(security, models.Security),
            ),
            request=req,
            error_status_codes=["4XX", "5XX"],
            retry_config=retry_config,
        )

        data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return utils.unmarshal_json(http_res.text, models.MessageResponse)
        if utils.match_response(http_res, "4XX", "application/json"):
            data = utils.unmarshal_json(http_res.text, models.ErrorResponseData)
            raise models.ErrorResponse(data=data)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models.SDKError(
                "API error occurred", http_res.status_code, http_res_text, http_res
            )

        content_type = http_res.headers.get("Content-Type")
        http_res_text = utils.stream_to_text(http_res)
        raise models.SDKError(
            f"Unexpected response received (code: {http_res.status_code}, type: {content_type})",
            http_res.status_code,
            http_res_text,
            http_res,
        )

    async def update_json_async(
        self,
        *,
        request: Union[
            models.UpdateWebhookMessageJSONRequest,
            models.UpdateWebhookMessageJSONRequestTypedDict,
        ],
        security: Optional[
            Union[
                models.UpdateWebhookMessageJSONSecurity,
                models.UpdateWebhookMessageJSONSecurityTypedDict,
            ]
        ] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
    ) -> models.MessageResponse:
        r"""
        :param request: The request object to send.
        :param security:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url

        if not isinstance(request, BaseModel):
            request = utils.unmarshal(request, models.UpdateWebhookMessageJSONRequest)
        request = cast(models.UpdateWebhookMessageJSONRequest, request)

        req = self.build_request_async(
            method="PATCH",
            path="/webhooks/{webhook_id}/{webhook_token}/messages/{message_id}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            security=utils.get_pydantic_model(
                security, Optional[models.UpdateWebhookMessageJSONSecurity]
            ),
            get_serialized_body=lambda: utils.serialize_request_body(
                request.incoming_webhook_update_request_partial,
                False,
                False,
                "json",
                models.IncomingWebhookUpdateRequestPartial,
            ),
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                operation_id="update_webhook_message_json",
                oauth2_scopes=[],
                security_source=get_security_from_env(security, models.Security),
            ),
            request=req,
            error_status_codes=["4XX", "5XX"],
            retry_config=retry_config,
        )

        data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return utils.unmarshal_json(http_res.text, models.MessageResponse)
        if utils.match_response(http_res, "4XX", "application/json"):
            data = utils.unmarshal_json(http_res.text, models.ErrorResponseData)
            raise models.ErrorResponse(data=data)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models.SDKError(
                "API error occurred", http_res.status_code, http_res_text, http_res
            )

        content_type = http_res.headers.get("Content-Type")
        http_res_text = await utils.stream_to_text_async(http_res)
        raise models.SDKError(
            f"Unexpected response received (code: {http_res.status_code}, type: {content_type})",
            http_res.status_code,
            http_res_text,
            http_res,
        )

    def update_form(
        self,
        *,
        request: Union[
            models.UpdateWebhookMessageFormRequest,
            models.UpdateWebhookMessageFormRequestTypedDict,
        ],
        security: Optional[
            Union[
                models.UpdateWebhookMessageFormSecurity,
                models.UpdateWebhookMessageFormSecurityTypedDict,
            ]
        ] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
    ) -> models.MessageResponse:
        r"""
        :param request: The request object to send.
        :param security:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url

        if not isinstance(request, BaseModel):
            request = utils.unmarshal(request, models.UpdateWebhookMessageFormRequest)
        request = cast(models.UpdateWebhookMessageFormRequest, request)

        req = self.build_request(
            method="PATCH",
            path="/webhooks/{webhook_id}/{webhook_token}/messages/{message_id}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            security=utils.get_pydantic_model(
                security, Optional[models.UpdateWebhookMessageFormSecurity]
            ),
            get_serialized_body=lambda: utils.serialize_request_body(
                request.incoming_webhook_update_request_partial,
                False,
                False,
                "form",
                models.IncomingWebhookUpdateRequestPartial,
            ),
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                operation_id="update_webhook_message_form",
                oauth2_scopes=[],
                security_source=get_security_from_env(security, models.Security),
            ),
            request=req,
            error_status_codes=["4XX", "5XX"],
            retry_config=retry_config,
        )

        data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return utils.unmarshal_json(http_res.text, models.MessageResponse)
        if utils.match_response(http_res, "4XX", "application/json"):
            data = utils.unmarshal_json(http_res.text, models.ErrorResponseData)
            raise models.ErrorResponse(data=data)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models.SDKError(
                "API error occurred", http_res.status_code, http_res_text, http_res
            )

        content_type = http_res.headers.get("Content-Type")
        http_res_text = utils.stream_to_text(http_res)
        raise models.SDKError(
            f"Unexpected response received (code: {http_res.status_code}, type: {content_type})",
            http_res.status_code,
            http_res_text,
            http_res,
        )

    async def update_form_async(
        self,
        *,
        request: Union[
            models.UpdateWebhookMessageFormRequest,
            models.UpdateWebhookMessageFormRequestTypedDict,
        ],
        security: Optional[
            Union[
                models.UpdateWebhookMessageFormSecurity,
                models.UpdateWebhookMessageFormSecurityTypedDict,
            ]
        ] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
    ) -> models.MessageResponse:
        r"""
        :param request: The request object to send.
        :param security:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url

        if not isinstance(request, BaseModel):
            request = utils.unmarshal(request, models.UpdateWebhookMessageFormRequest)
        request = cast(models.UpdateWebhookMessageFormRequest, request)

        req = self.build_request_async(
            method="PATCH",
            path="/webhooks/{webhook_id}/{webhook_token}/messages/{message_id}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            security=utils.get_pydantic_model(
                security, Optional[models.UpdateWebhookMessageFormSecurity]
            ),
            get_serialized_body=lambda: utils.serialize_request_body(
                request.incoming_webhook_update_request_partial,
                False,
                False,
                "form",
                models.IncomingWebhookUpdateRequestPartial,
            ),
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                operation_id="update_webhook_message_form",
                oauth2_scopes=[],
                security_source=get_security_from_env(security, models.Security),
            ),
            request=req,
            error_status_codes=["4XX", "5XX"],
            retry_config=retry_config,
        )

        data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return utils.unmarshal_json(http_res.text, models.MessageResponse)
        if utils.match_response(http_res, "4XX", "application/json"):
            data = utils.unmarshal_json(http_res.text, models.ErrorResponseData)
            raise models.ErrorResponse(data=data)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models.SDKError(
                "API error occurred", http_res.status_code, http_res_text, http_res
            )

        content_type = http_res.headers.get("Content-Type")
        http_res_text = await utils.stream_to_text_async(http_res)
        raise models.SDKError(
            f"Unexpected response received (code: {http_res.status_code}, type: {content_type})",
            http_res.status_code,
            http_res_text,
            http_res,
        )

    def update_multipart(
        self,
        *,
        request: Union[
            models.UpdateWebhookMessageMultipartRequest,
            models.UpdateWebhookMessageMultipartRequestTypedDict,
        ],
        security: Optional[
            Union[
                models.UpdateWebhookMessageMultipartSecurity,
                models.UpdateWebhookMessageMultipartSecurityTypedDict,
            ]
        ] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
    ) -> models.MessageResponse:
        r"""
        :param request: The request object to send.
        :param security:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url

        if not isinstance(request, BaseModel):
            request = utils.unmarshal(
                request, models.UpdateWebhookMessageMultipartRequest
            )
        request = cast(models.UpdateWebhookMessageMultipartRequest, request)

        req = self.build_request(
            method="PATCH",
            path="/webhooks/{webhook_id}/{webhook_token}/messages/{message_id}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            security=utils.get_pydantic_model(
                security, Optional[models.UpdateWebhookMessageMultipartSecurity]
            ),
            get_serialized_body=lambda: utils.serialize_request_body(
                request.request_body,
                False,
                False,
                "multipart",
                models.UpdateWebhookMessageMultipartRequestBody,
            ),
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                operation_id="update_webhook_message_multipart",
                oauth2_scopes=[],
                security_source=get_security_from_env(security, models.Security),
            ),
            request=req,
            error_status_codes=["4XX", "5XX"],
            retry_config=retry_config,
        )

        data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return utils.unmarshal_json(http_res.text, models.MessageResponse)
        if utils.match_response(http_res, "4XX", "application/json"):
            data = utils.unmarshal_json(http_res.text, models.ErrorResponseData)
            raise models.ErrorResponse(data=data)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models.SDKError(
                "API error occurred", http_res.status_code, http_res_text, http_res
            )

        content_type = http_res.headers.get("Content-Type")
        http_res_text = utils.stream_to_text(http_res)
        raise models.SDKError(
            f"Unexpected response received (code: {http_res.status_code}, type: {content_type})",
            http_res.status_code,
            http_res_text,
            http_res,
        )

    async def update_multipart_async(
        self,
        *,
        request: Union[
            models.UpdateWebhookMessageMultipartRequest,
            models.UpdateWebhookMessageMultipartRequestTypedDict,
        ],
        security: Optional[
            Union[
                models.UpdateWebhookMessageMultipartSecurity,
                models.UpdateWebhookMessageMultipartSecurityTypedDict,
            ]
        ] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
    ) -> models.MessageResponse:
        r"""
        :param request: The request object to send.
        :param security:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url

        if not isinstance(request, BaseModel):
            request = utils.unmarshal(
                request, models.UpdateWebhookMessageMultipartRequest
            )
        request = cast(models.UpdateWebhookMessageMultipartRequest, request)

        req = self.build_request_async(
            method="PATCH",
            path="/webhooks/{webhook_id}/{webhook_token}/messages/{message_id}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            security=utils.get_pydantic_model(
                security, Optional[models.UpdateWebhookMessageMultipartSecurity]
            ),
            get_serialized_body=lambda: utils.serialize_request_body(
                request.request_body,
                False,
                False,
                "multipart",
                models.UpdateWebhookMessageMultipartRequestBody,
            ),
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                operation_id="update_webhook_message_multipart",
                oauth2_scopes=[],
                security_source=get_security_from_env(security, models.Security),
            ),
            request=req,
            error_status_codes=["4XX", "5XX"],
            retry_config=retry_config,
        )

        data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return utils.unmarshal_json(http_res.text, models.MessageResponse)
        if utils.match_response(http_res, "4XX", "application/json"):
            data = utils.unmarshal_json(http_res.text, models.ErrorResponseData)
            raise models.ErrorResponse(data=data)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models.SDKError(
                "API error occurred", http_res.status_code, http_res_text, http_res
            )

        content_type = http_res.headers.get("Content-Type")
        http_res_text = await utils.stream_to_text_async(http_res)
        raise models.SDKError(
            f"Unexpected response received (code: {http_res.status_code}, type: {content_type})",
            http_res.status_code,
            http_res_text,
            http_res,
        )
